apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: k8s-spring-boot-example
  name: k8s-spring-boot-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-spring-boot-example
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: k8s-spring-boot-example
    spec:
      containers:
      - image: localhost:5000/apps/spring-boot-example
        name: k8s-spring-boot-example
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        startupProbe:
          httpGet:
            port: http
            path: /actuator/health
          timeoutSeconds: 10
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 30
        readinessProbe:
          httpGet:
            port: http
            path: /actuator/health/readiness
          timeoutSeconds: 10
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            port: http
            path: /actuator/health/liveness
          timeoutSeconds: 10
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        lifecycle:
          preStop:
            exec:
              command:
                - sh
                - '-c'
                - sleep 10
        resources:
          limits:
            memory: 1024Mi
          requests:
            cpu: 125m
            memory: 1024Mi
      terminationGracePeriodSeconds: 45
status: {}
