apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: k8s-spring-boot-example
  name: k8s-spring-boot-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-spring-boot-example
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: k8s-spring-boot-example
    spec:
      containers:
      - image: localhost:5000/apps/spring-boot-example
        name: k8s-spring-boot-example
        startupProbe:
          httpGet:
            port: 8080
            path: /actuator/health
          timeoutSeconds: 10
          failureThreshold: 30
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/readiness
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/liveness
          timeoutSeconds: 10
        lifecycle:
          preStop:
            exec:
              command:
                - sh
                - '-c'
                - sleep 10
        resources:
          limits:
            cpu: 500m
            memory: 2Gi
          requests:
            cpu: 125m
            memory: 512Mi
status: {}
